// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarea9y10.Data;

namespace Tarea9y10.Migrations
{
    [DbContext(typeof(PersonaDbContext))]
    [Migration("20201107220033_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("Tarea9y10.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Causas")
                        .HasColumnType("TEXT");

                    b.Property<string>("CiudadNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("CiudadResidencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Denominacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Disciplinado")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocuIdentidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpulsadoIns")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaAceptado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaBautismo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaConversion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Funciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hijos")
                        .HasColumnType("TEXT");

                    b.Property<string>("IglesiaAnterior")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metas")
                        .HasColumnType("TEXT");

                    b.Property<string>("MinisterioLlamado")
                        .HasColumnType("TEXT");

                    b.Property<string>("MinisterioMayorFruto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ministerios")
                        .HasColumnType("TEXT");

                    b.Property<string>("NivelEstudio")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreEmpresa")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreIglesia")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombrePastor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaisNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaisResidencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profesion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Razon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Respaldo")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoEmp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("TEXT");

                    b.Property<string>("apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("celular")
                        .HasColumnType("TEXT");

                    b.Property<string>("correo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("genero")
                        .HasColumnType("TEXT");

                    b.Property<string>("img")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("telefonoPer")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonaId");

                    b.ToTable("personas");

                    b.HasData(
                        new
                        {
                            PersonaId = 1,
                            Causas = "Me iban a expulsar",
                            CiudadNacimiento = "Santo domingo",
                            CiudadResidencia = "Santo domingo este",
                            Denominacion = "Católica",
                            Direccion = "Santo domingo este",
                            Disciplinado = "Si",
                            DocuIdentidad = "4554545454",
                            EstadoCivil = "Soltero",
                            ExpulsadoIns = "No",
                            FechaAceptado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaBautismo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaConversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Funciones = "Diacono",
                            Hijos = "No",
                            IglesiaAnterior = "Dios es mi vida",
                            Metas = "Ser el mejor",
                            MinisterioLlamado = "Ministerios de damas",
                            MinisterioMayorFruto = "Ministerios de damas",
                            Ministerios = "Ministerios de damas",
                            NivelEstudio = "Tecnico",
                            NombreEmpresa = "--",
                            NombreIglesia = "Jesus en mi vida",
                            Ocupacion = "--",
                            PaisNacimiento = "RD",
                            PaisResidencia = "RD",
                            Profesion = "Ninguna",
                            Razon = "--",
                            Respaldo = "Si",
                            TelefonoEmp = "--",
                            TipoDocumento = "Cedula",
                            apellido = "Rodriguez",
                            celular = "849-280-9438",
                            correo = "roberticor05@gmail.com",
                            fechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            genero = "Masculino",
                            nombre = "Roberto",
                            telefonoPer = "849-280-9438"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
